package de.cooperateproject.incrementalsync.dbutils.statement

import java.io.{File, PrintWriter}
import java.util.Calendar

/**
  * Provides Utility methods to work with sql files and statements.
  */
object SQLUtil {

  private val HEADLINE =
    """/*------------------------------------------------------------*/
      |/* Generated by HibernateTrigger (Sebastian Hahner)           */
      |/* Created on: <date>                  */
      |/* DBMS      : MySql                                          */
      |/* Notes     : Creates Tables and Triggers from Hibernate XML */
      |/*------------------------------------------------------------*/
    """.stripMargin.replace("<date>", Calendar.getInstance.getTime.toString)

  /**
    * Takes a list of generated statements and writes a sql file.
    *
    * @param sqlFile    the destination sql file
    * @param statements a list of statements
    */
  def writeSQL(sqlFile: File, statements: List[Statement]): Unit = {

    var outputString = HEADLINE + "\n\n"

    for (statement <- statements) {
      outputString += statement.toString + "\n\n"
    }

    writeWithPrintWriter(sqlFile, outputString, "Saved sql file to ", "ERROR while saving sql file!")
  }

  def writeWithPrintWriter(file: File, content: String, successMessage: String, exceptionMessage: String): Unit = {
    var writer: PrintWriter = null
    try {
      writer = new PrintWriter(file)
      writer.write(content)
      println(successMessage + file.getAbsolutePath)
    } catch {
      case _: Exception => println(exceptionMessage)
    } finally {
      writer.close()
    }
  }

}
